refactor(models): use postgresql ARRAY instead of base (#9075)
We need to use the object from postgresql dialect for our ARRAYs because the base object does not implement `contains` and maybe other basic functions.

Solves: NotImplementedError: ARRAY.contains() not implemented for the base ARRAY type; please use the dialect-specific ARRAY type