test: increase gitter credentials cache (#9732)
This might be the cause of all the errors like this we sometimes encounter in record mode:
```
mergify_engine.gitter.GitError: (128, "fatal: could not read Username for
'https://github.com/mergifyio-testing/functional-testing-repo-Greesb':
terminal prompts disabled\n")
```

Because if the cache expires, after the 300s we set, then git needs to ask the credentials again.