chore(queue): adding logging if draft pr is empty (#7141)
It's supposed to be impossible, but we still have a couple of GitHub
error reporting during TrainCar creation:
```
mergify_engine.clients.http.HTTPClientSideError: 422 Client Error: Unprocessable Entity for url `https://api.github.com/repos/productboard/pb-frontend/pulls`
Details: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between master and mergify/merge-queue/f2da349ae6"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}
```

This change is to ensure we don't make erroneous hypothesis about this error
message.

I pick `log.error` instead of `RuntimeError` to not block the merge-queue when the
issue occurs.

Later if no Sentry errors are reported, I will switch to `RuntimeError`.

Related MRGFY-2481