ci: Fix compare-github-requests.sh for new fixture (#9196)
When a new fixture is created, it doesn't exist in head and lead to this error when msgpack try to unpack it: 

```
fatal: path 'zfixtures/cassettes/TestLogEmbedderGithubAction/test_ci_issue_gpt_grouping_accuracy/http.msgpack' exists on disk, but not in 'HEAD~3'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/.local/lib/python3.10/site-packages/msgpack/__init__.py", line 47, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 205, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
/home/runner/work/_temp/compare-github-requests.sh: line 20: 11-: syntax error: operand expected (error token is "-")
Error: Process completed with exit code 1.
Error: Unable to process file command 'output' successfully.
Error: Invalid value. Matching delimiter not found 'FYEEYenVDXr4QBiGs32k'
```

This fix this error

Change-Id: I476f3b7a6783ab628d4aafdb6eef5ebb01dfa2b0