fix(queue/statistics): Do not compute fmean with no stats (#1006)
Otherwise `statistics.fmean` throws an exception because it requires at
least one datapoint:
statistics.StatisticsError: fmean requires at least one data point